### ISSUE TITLE
Intel HD 4000

### ISSUE THREAD

**Issue by behroozramezani** [pesintta/vdr-plugin-softhddevice#16]
Hello 
I need use this plugin on Intel HD 4000. Does this plugin support vaapi?

**Comment by rofafor** [comment]
The original softhddevice plugin already supports vaapi, but this fork also supports vaapi post-processing. Please, take a look at this posting: http://www.vdr-portal.de/board17-developer/board21-vdr-plugins/p1228505-announce-va-api-vpp-support-for-vdr-plugin-softhddevice/#post1228505

**Comment by behroozramezani** [comment]
Thanks a lot 
I will install softhddevice on Intel HD 4000. If I have any issue. Can you help me?

**Comment by pesintta** [comment]
Depends on the issue. For getting softhddevice to run you should contact the original author. For vaapi postprocessing we may be able to help.

Though I suspect HD 4000 does not have many postprocessing capabilities.
