### ISSUE TITLE
VPP-Branch / VA-API 2.0 Compile Error

### ISSUE THREAD

**Issue by Quantomax** [pesintta/vdr-plugin-softhddevice#23]
Hi,

after getting vaapi 2.0 by debian buster update, softhddevice stops working and recompiling fails with:
[..]
In file included from video.c:172:0:
/usr/include/x86_64-linux-gnu/libavcodec/vaapi.h:56:29: note: declared here
 struct attribute_deprecated vaapi_context {
                             ^~~~~~~~~~~~~
video.c: In function ‘VaapiInit’:
video.c:2772:5: error: too few arguments to function ‘vaSetErrorCallback’
     vaSetErrorCallback(NULL);
     ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/va/va_x11.h:27:0,
                 from video.c:136:
/usr/include/va/va.h:270:19: note: declared here
 VAMessageCallback vaSetErrorCallback(VADisplay dpy, VAMessageCallback callback, void *user_context);
                   ^~~~~~~~~~~~~~~~~~
video.c:2773:5: error: too few arguments to function ‘vaSetInfoCallback’
     vaSetInfoCallback(NULL);
     ^~~~~~~~~~~~~~~~~
In file included from /usr/include/va/va_x11.h:27:0,
                 from video.c:136:
/usr/include/va/va.h:276:19: note: declared here
 VAMessageCallback vaSetInfoCallback(VADisplay dpy, VAMessageCallback callback, void *user_context);
                   ^~~~~~~~~~~~~~~~~

**Comment by pesintta** [comment]
Fixed in #24
